/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DroneDesign {
  'name' : string,
  'timestamp' : bigint,
  'designData' : string,
}
export interface Part {
  'id' : string,
  'weight' : number,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'isSample' : boolean,
  'specs' : string,
  'imageUrl' : [] | [string],
  'category' : PartCategory,
}
export type PartCategory = { 'propeller' : null } |
  { 'frame' : null } |
  { 'motor' : null } |
  { 'flightController' : null } |
  { 'camera' : null } |
  { 'battery' : null };
export interface PartInput {
  'id' : string,
  'weight' : number,
  'name' : string,
  'specs' : string,
  'imageUrl' : [] | [string],
  'category' : PartCategory,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDesign' : ActorMethod<[string], undefined>,
  'deletePart' : ActorMethod<[string], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesign' : ActorMethod<[string], [] | [DroneDesign]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDesigns' : ActorMethod<[], Array<DroneDesign>>,
  'listParts' : ActorMethod<[], Array<Part>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDesign' : ActorMethod<[string, string], undefined>,
  'savePart' : ActorMethod<[PartInput], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];