/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DroneDesign = IDL.Record({
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'designData' : IDL.Text,
});
export const PartCategory = IDL.Variant({
  'propeller' : IDL.Null,
  'frame' : IDL.Null,
  'motor' : IDL.Null,
  'flightController' : IDL.Null,
  'camera' : IDL.Null,
  'battery' : IDL.Null,
});
export const Part = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Float64,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isSample' : IDL.Bool,
  'specs' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : PartCategory,
});
export const PartInput = IDL.Record({
  'id' : IDL.Text,
  'weight' : IDL.Float64,
  'name' : IDL.Text,
  'specs' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : PartCategory,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDesign' : IDL.Func([IDL.Text], [], []),
  'deletePart' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesign' : IDL.Func([IDL.Text], [IDL.Opt(DroneDesign)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDesigns' : IDL.Func([], [IDL.Vec(DroneDesign)], ['query']),
  'listParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'savePart' : IDL.Func([PartInput], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DroneDesign = IDL.Record({
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'designData' : IDL.Text,
  });
  const PartCategory = IDL.Variant({
    'propeller' : IDL.Null,
    'frame' : IDL.Null,
    'motor' : IDL.Null,
    'flightController' : IDL.Null,
    'camera' : IDL.Null,
    'battery' : IDL.Null,
  });
  const Part = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Float64,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isSample' : IDL.Bool,
    'specs' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : PartCategory,
  });
  const PartInput = IDL.Record({
    'id' : IDL.Text,
    'weight' : IDL.Float64,
    'name' : IDL.Text,
    'specs' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : PartCategory,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDesign' : IDL.Func([IDL.Text], [], []),
    'deletePart' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesign' : IDL.Func([IDL.Text], [IDL.Opt(DroneDesign)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDesigns' : IDL.Func([], [IDL.Vec(DroneDesign)], ['query']),
    'listParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'savePart' : IDL.Func([PartInput], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };